const COPART_RATES = {
  'ABILENE - TX': [null,null,null,1750,null,null],
  'ADELANTO - CA': [null,null,2000,null,null,null],
  'AKRON - OH': [null,1650,null,null,null,null],
  'ALBANY - NY': [null,1400,null,null,null,null],
  'ALBUQUERQUE - NM': [null,null,2490,1970,null,null],
  'ALTOONA - PA': [null,1590,null,null,null,null],
  'AMARILLO - TX': [null,null,null,1690,null,null],
  'ANCHORAGE - AK': [null,null,null,null,3570,null],
  'ANCHORAGE SOUTH - AK': [null,null,null,null,3570,null],
  'ANDREWS-TX': [null,null,null,1770,null,null],
  'ANTELOPE - CA': [null,null,2110,null,null,null],
  'APPLETON - WI': [1850,null,null,null,null,null],
  'ATLANTA EAST - GA': [1450,null,null,null,null,null],
  'ATLANTA NORTH - GA': [1450,null,null,null,null,null],
  'ATLANTA SOUTH - GA': [1450,null,null,null,null,null],
  'ATLANTA WEST - GA': [1450,null,null,null,null,null],
  'AUGUSTA - GA': [1450,null,null,null,null,null],
  'AUSTIN - TX': [null,null,null,1650,null,null],
  'BAKERSFIELD - CA': [null,null,2000,null,null,null],
  'BALTIMORE - MD': [null,1550,null,null,null,null],
  'BALTIMORE EAST-MD': [null,1550,null,null,null,null],
  'BATON ROUGE - LA': [1550,null,null,null,null,null],
  'BILLINGS - MT': [null,null,null,2500,2570,null],
  'BIRMINGHAM - AL': [1550,null,null,null,null,null],
  'BISMARCK - ND': [null,2450,null,null,null,null],
  'BOISE - ID': [null,null,null,null,2192,null],
  'BUFFALO - NY': [null,1650,null,null,null,null],
  'CANDIA - NH': [null,1650,null,null,null,null],
  'CARTERSVILLE - GA': [1400,null,null,null,null,null],
  'CASPER - WY': [null,null,null,null,3017,null],
  'CHAMBERSBURG - PA': [null,1500,null,null,null,null],
  'CHARLESTON - SC': [1350,null,null,null,null,null],
  'CHARLESTON - WV': [null,1617,null,null,null,null],
  'CHICAGO NORTH - IL': [null,1750,null,null,null,null],
  'CHICAGO SOUTH - IL': [null,1750,null,null,null,null],
  'CHINA GROVE - NC': [1390,null,null,null,null,null],
  'CICERO-IN': [null,1750,null,null,null,null],
  'CLEVELAND EAST - OH': [null,1590,null,null,null,null],
  'CLEVELAND WEST - OH': [null,1590,null,null,null,null],
  'COLORADO SPRINGS - CO': [null,null,2430,2505,null,null],
  'COLUMBIA - MO': [1750,null,null,null,null,null],
  'COLUMBIA - SC': [1320,null,null,null,null,null],
  'COLUMBUS - OH': [null,1620,null,null,null,null],
  'CONCORD - NC': [1390,null,null,null,null,null],
  'CORPUS CHRISTI - TX': [null,null,null,1570,null,null],
  'CRASHEDTOYS ATLANTA': [1370,null,null,null,null,null],
  'CRASHEDTOYS DALLAS- TX': [null,null,null,1570,null,null],
  'CRASHEDTOYS EAST BETHEL - MN': [null,1770,null,null,null,null],
  'CRASHEDTOYS ELDRIDGE - IA': [null,2050,null,null,null,null],
  'CRASHEDTOYS MINNEAPOLIS-MN': [null,2150,null,null,null,null],
  'CRASHEDTOYS SACRAMENTO - CA': [null,null,2100,null,null,null],
  'CULPEPER - VA': [null,1690,null,null,null,null],
  'DALLAS - TX': [null,null,null,1590,null,null],
  'DALLAS SOUTH - TX': [null,null,null,1590,null,null],
  'DANVILLE - VA': [1520,null,null,null,null,null],
  'DAVENPORT - IA': [null,1790,null,null,null,null],
  'DAYTON - OH': [null,1640,null,null,null,null],
  'DENVER - CO': [null,null,2430,1950,null,null],
  'DENVER CENTRAL - CO': [null,null,2430,1950,null,null],
  'DENVER SOUTH - CO': [null,null,2430,1950,null,null],
  'DES MOINES - IA': [null,1740,null,null,null,null],
  'DETROIT - MI': [null,1640,null,null,null,null],
  'DOTHAN - AL': [1420,null,null,null,null,null],
  'DYER - IN': [1667,null,null,null,null,null],
  'EARLINGTON – KY': [1590,null,null,null,null,null],
  'EL PASO - TX': [null,null,null,1720,null,null],
  'EUGENE - OR': [null,null,null,null,2090,null],
  'EXETER - RI': [null,1450,null,null,null,null],
  'FAIRBURN - GA': [1450,null,null,null,null,null],
  'FAYETTEVILLE - AR': [null,null,null,1750,null,null],
  'FLINT - MI': [null,1670,null,null,null,null],
  'FORT WAYNE - IN': [null,1720,null,null,null,null],
  'FREDERICKSBURG - VA': [null,1450,null,null,null,null],
  'FREETOWN – MA': [null,1500,null,null,null,null],
  'FREMONT - CA': [null,null,2080,null,null,null],
  'FRESNO - CA': [null,null,2030,null,null,null],
  'FT.PIERCE - FL': [1400,null,null,null,null,null],
  'FT.WORTH - TX': [null,null,null,1550,null,null],
  'Freetown – MA': [null,1500,null,null,null,null],
  'GASTONIA - NC': [1450,null,null,null,null,null],
  'GLASSBORO EAST - NJ': [null,1370,null,null,null,null],
  'GLASSBORO WEST-NJ': [null,1370,null,null,null,null],
  'GRAHAM - WA': [null,null,null,null,1950,null],
  'GREER - SC': [1400,null,null,null,null,null],
  'GRENADA - MS': [1550,null,null,null,null,null],
  'HAMMOND - IN': [null,1720,null,null,null,null],
  'HAMPTON - VA': [null,1470,null,null,null,null],
  'HARRISBURG - PA': [null,1450,null,null,null,null],
  'HARTFORD - CT': [null,1450,null,null,null,null],
  'HARTFORD SPRINGFIELD-CT': [null,1400,null,null,null,null],
  'HAYWARD - CA': [null,null,2100,null,null,null],
  'HELENA - MT': [null,null,null,null,2450,null],
  'HONOLULU - HI': [null,null,3600,null,null,null],
  'HOUSTON - TX': [null,null,null,1520,null,null],
  'HOUSTON EAST-TX': [null,null,null,1520,null,null],
  'INDIANAPOLIS - IN': [1670,null,null,null,null,null],
  'IONIA - MI': [null,1770,null,null,null,null],
  'JACKSON - MS': [1500,null,null,null,null,null],
  'JACKSONVILLE EAST - FL': [1350,null,null,null,null,null],
  'JACKSONVILLE NORTH -FL': [1350,null,null,null,null,null],
  'JACKSONVILLE WEST - FL': [1350,null,null,null,null,null],
  'KANSAS CITY - KS': [1690,null,null,null,null,null],
  'KANSAS CITY EAST': [1690,null,null,null,null,null],
  'KINCHELOE - MI': [null,2090,null,null,null,null],
  'KNOXVILLE - TN': [1450,null,null,null,null,null],
  'LANSING - MI': [null,1770,null,null,null,null],
  'LAS VEGAS - NV': [null,null,2080,null,null,null],
  'LAS VEGAS WEST - NV': [null,null,2080,null,null,null],
  'LEXINGTON EAST - KY': [1590,null,null,null,null,null],
  'LEXINGTON WEST - KY': [1590,null,null,null,null,null],
  'LINCOLN - NE': [null,1750,null,null,null,null],
  'LITTLE ROCK - AR': [1590,null,null,null,null,null],
  'LONG BEACH - CA': [null,null,1890,null,null,null],
  'LONG ISLAND - NY': [null,1420,null,null,null,null],
  'LONGVIEW - TX': [null,null,null,1590,null,null],
  'LOS ANGELES - CA': [null,null,1950,null,null,null],
  'LOUISVILLE - KY': [1650,null,null,null,null,null],
  'LUFKIN - TX': [null,null,null,1570,null,null],
  'LUMBERTON - NC': [1420,null,null,null,null,null],
  'LYMAN - ME': [null,1570,null,null,null,null],
  'MACON - GA': [1370,null,null,null,null,null],
  'MADISON - WI': [1750,null,null,null,null,null],
  'MADISON SOUTH - WI': [1750,null,null,null,null,null],
  'MARTINEZ - CA': [null,null,2100,null,null,null],
  'MCALLEN - TX': [null,null,null,1590,null,null],
  'MEBANE - NC': [1420,null,null,null,null,null],
  'MEMPHIS - TN': [1620,null,null,null,null,null],
  'MENTONE - CA': [null,null,2030,null,null,null],
  'MIAMI CENTRAL - FL': [1450,null,null,null,null,null],
  'MIAMI NORTH - FL': [1450,null,null,null,null,null],
  'MIAMI SOUTH - FL': [1450,null,null,null,null,null],
  'MILWAUKEE - WI': [null,1770,null,null,null,null],
  'MILWAUKEE NORTH-WI': [null,1770,null,null,null,null],
  'MILWAUKEE SOUTH - WI': [null,1770,null,null,null,null],
  'MINNEAPOLIS - MN': [2000,1790,null,null,null,null],
  'MINNEAPOLIS NORTH - MN': [2000,1790,null,null,null,null],
  'MOBILE - AL': [1450,null,null,null,null,null],
  'MOBILE SOUTH - AL': [1450,null,null,null,null,null],
  'MOCKSVILLE - NC': [1420,null,null,null,null,null],
  'MONTGOMERY - AL': [1420,null,null,null,null,null],
  'NASHVILLE - TN': [1550,null,null,null,null,null],
  'NEW ORLEANS - LA': [1520,null,null,null,null,null],
  'NEWBURGH - NY': [null,1420,null,null,null,null],
  'NORTH BOSTON - MA': [null,1500,null,null,null,null],
  'NORTH CHARLESTON': [1350,null,null,null,null,null],
  'NORTH SEATTLE - WA': [null,null,null,null,1950,null],
  'OCALA - FL': [1450,null,null,null,null,null],
  'OGDEN- UT': [null,null,2200,null,null,null],
  'OKLAHOMA CITY - OK': [null,null,null,1750,null,null],
  'ORLANDO - FL': [1420,null,null,null,null,null],
  'ORLANDO NORTH - FL': [1420,null,null,null,null,null],
  'ORLANDO SOUTH - FL': [1420,null,null,null,null,null],
  'PASCO - WA': [null,null,null,null,2100,null],
  'PEORIA - IL': [null,1770,null,null,null,null],
  'PHILADELPHIA - PA': [null,1400,null,null,null,null],
  'PHILADELPHIA EAST': [null,1400,null,null,null,null],
  'PHILADELPHIA EAST - SUBLOT - PA': [null,1400,null,null,null,null],
  'PHOENIX - AZ': [null,null,1500,null,null,null],
  'PHOENIX NORTH - AZ': [null,null,1500,null,null,null],
  'PITTSBURG SOUTH - PA': [null,1590,null,null,null,null],
  'PITTSBURGH EAST - PA': [null,1600,null,null,null,null],
  'PITTSBURGH NORTH - PA': [null,1600,null,null,null,null],
  'PITTSBURGH WEST - PA': [null,1600,null,null,null,null],
  'PORTLAND NORTH - OR': [null,null,null,null,1990,null],
  'PORTLAND SOUTH - OR': [null,null,null,null,1990,null],
  'PUNTA GORDA - FL': [1450,null,null,null,null,null],
  'PUNTA GORDA SOUTH - FL': [1450,null,null,null,null,null],
  'RALEIGH - NC': [1420,null,null,null,null,null],
  'RALEIGH NORTH - NC': [1420,null,null,null,null,null],
  'RANCHO CUCAMONGA - CA': [null,null,1950,null,null,null],
  'RAPID CITY - SD': [null,2300,null,null,2900,null],
  'REDDING - CA': [null,null,2200,null,null,null],
  'RENO - NV': [null,null,2100,null,null,null],
  'RICHMOND - VA': [null,1550,null,null,null,null],
  'RICHMOND EAST-VA': [null,1550,null,null,null,null],
  'ROCHESTER - NY': [null,1570,null,null,null,null],
  'RUTLAND - VT': [null,1650,null,null,null,null],
  'SACRAMENTO - CA': [null,null,2100,null,null,null],
  'SALT LAKE CITY - UT': [null,null,2150,null,null,null],
  'SAN ANTONIO - TX': [null,null,null,1590,null,null],
  'SAN BERNARDINO- CA': [null,null,1950,null,null,null],
  'SAN DIEGO - CA': [null,null,1990,null,null,null],
  'SAN JOSE - CA': [null,null,2100,null,null,null],
  'SAVANNAH - GA': [1200,null,null,null,null,null],
  'SCRANTON - PA': [null,1450,null,null,null,null],
  'SEAFORD - DE': [null,1470,null,null,null,null],
  'SHREVEPORT - LA': [null,null,null,1620,null,null],
  'SIKESTON - MO': [1750,null,null,null,null,null],
  'SO SACRAMENTO - CA': [null,null,2100,null,null,null],
  'SOMERVILLE - NJ': [null,1350,null,null,null,null],
  'SOUTH BOSTON - MA': [null,1500,null,null,null,null],
  'SOUTHERN ILLINOIS - IL': [1690,null,null,null,null,null],
  'SPARTANBURG - SC': [1420,null,null,null,null,null],
  'SPOKANE - WA': [null,null,null,null,2100,null],
  'SPRINGFIELD - MO': [1720,null,null,null,null,null],
  'ST. CLOUD - MN': [null,1850,null,null,null,null],
  'ST. LOUIS - MO': [1720,null,null,null,null,null],
  'SUN VALLEY - CA': [null,null,1950,null,null,null],
  'SYRACUSE - NY': [null,1490,null,null,null,null],
  'TALLAHASSEE - FL': [1420,null,null,null,null,null],
  'TAMPA SOUTH - FL': [1420,null,null,null,null,null],
  'TANNER - AL': [1520,null,null,null,null,null],
  'TIFTON - GA': [1400,null,null,null,null,null],
  'TORONTO CANADA': [null,null,null,null,null,null],
  'TRENTON - NJ': [null,1400,null,null,null,null],
  'TUCSON - AZ': [null,null,2100,null,null,null],
  'TULSA - OK': [null,null,null,1790,null,null],
  'VALLEJO - CA': [null,null,2100,null,null,null],
  'VAN NUYS - CA': [null,null,1990,null,null,null],
  'WACO - TX': [null,null,null,1590,null,null],
  'WALTON - KY': [1650,null,null,null,null,null],
  'WASHINGTON DC - MD': [null,1470,null,null,null,null],
  'WAYLAND - MI': [null,1820,null,null,null,null],
  'WEBSTER - NH': [null,null,null,null,null,null],
  'WEST PALM BEACH - FL': [1470,null,null,null,null,null],
  'WEST WARREN - MA': [null,1500,null,null,null,null],
  'WHEELING - IL': [null,1720,null,null,null,null],
  'WICHITA - KS': [null,null,null,1790,null,null],
  'WINDHAM - ME': [null,1670,null,null,null,null],
  'YORK HAVEN - PA': [null,1450,null,null,null,null],
};