const COPART_RATES = {
  'ABILENE - TX': [null,null,null,425,null,null],
  'ACE - PERRIS 2 - CA': [null,null,200,null,null,null],
  'ACE CARSON - CA': [null,null,150,null,null,null],
  'ACE-PERRIS': [null,null,200,null,null,null],
  'ACRON CANTON - OH': [null,475,null,null,null,null],
  'ADELANTO - CA': [null,null,225,null,null,null],
  'ADESA BIRMINGHAM - AL': [350,null,null,null,null,null],
  'ADESA Brashers': [null,null,400,null,null,null],
  'ADESA CHICAGO - IL': [null,null,null,null,null,null],
  'ADESA GOLDEN GATE - CA': [null,null,400,null,null,null],
  'ADESA KANSAS CITY - MO': [550,null,null,null,null,null],
  'ADESA MERCER - PA': [null,450,null,null,null,null],
  'ADESA NORTHWEST - WA': [null,null,700,null,325,null],
  'ADESA PA - PA': [null,275,null,null,null,null],
  'ADESA QUEEN CITY - OH': [null,null,null,null,null,null],
  'ADESA SEATTLE - WA': [null,null,800,null,225,null],
  'ADESA WASHINGTON DC - VA': [null,375,null,null,null,350],
  'AKRON - OH': [null,475,null,null,null,null],
  'ALBANY - NY': [null,250,null,null,null,null],
  'ALBUQUERQUE - NM': [null,null,700,700,null,null],
  'ALTOONA - PA': [null,425,null,null,null,null],
  'AMARILLO - TX': [null,null,null,425,null,null],
  'ANAHEIM - CA': [null,null,160,null,null,null],
  'ANAHEIM CONSOLIDATED – CA': [null,null,null,null,null,null],
  'ANCHORAGE - AK': [null,null,2650,null,1850,null],
  'ANCHORAGE SOUTH - AK': [null,null,2650,null,1850,null],
  'ANDREWS-TX': [null,null,null,450,null,null],
  'ANTELOPE - CA': [null,null,350,null,null,null],
  'APPLETON - WI': [725,null,null,null,null,null],
  'ASHEVILLE - NC': [325,null,null,null,null,325],
  'ASHLAND - KY': [700,null,null,null,null,null],
  'ATLANTA - GA': [300,null,null,null,null,null],
  'ATLANTA EAST - GA': [300,null,null,null,null,null],
  'ATLANTA NORTH - GA': [300,null,null,null,null,null],
  'ATLANTA SOUTH - GA': [300,null,null,null,null,null],
  'ATLANTA WEST - GA': [300,null,null,null,null,null],
  'AUGUSTA - GA': [300,null,null,null,null,null],
  'AUSTIN - TX': [null,null,null,275,null,null],
  'AUSTIN NORTH - TX': [null,null,null,275,null,null],
  'AVENEL - NJ': [null,150,null,null,null,null],
  'BAKERSFIELD - CA': [null,null,250,null,null,null],
  'BALTIMORE - MD': [null,300,null,null,null,300],
  'BALTIMORE - MD (White Marsh)': [null,300,null,null,null,300],
  'BALTIMORE EAST - MD': [null,300,null,null,null,300],
  'BATON ROUGE - LA': [400,null,null,null,null,null],
  'BILLINGS - MT': [null,null,1050,1250,850,null],
  'BIRMINGHAM - AL': [375,null,null,null,null,null],
  'BISMARCK - ND': [null,1300,null,null,null,null],
  'BOISE - ID': [null,null,750,null,475,null],
  'BOSTON - MA': [null,375,null,null,null,null],
  'BOSTON-SHIRLEY - MA': [null,350,null,null,null,null],
  'BOWLING GREEN - KY': [550,null,null,null,null,null],
  'BRIDGEPORT - PA': [null,250,null,null,null,null],
  'BUCKHANNON - WV': [null,500,null,null,null,500],
  'BUFFALO - NY': [null,475,null,null,null,null],
  'BUFFALO - NY (Alden Sublot)': [null,500,null,null,null,null],
  'BURLINGTON - VT': [null,500,null,null,null,null],
  'CANDIA - NH': [null,375,null,null,null,null],
  'CARTERSVILLE - GA': [300,null,null,null,null,null],
  'CASPER - WY': [null,null,1400,null,1300,null],
  'CASPER WEST - WY': [null,null,1400,null,1300,null],
  'CEDAR RAPIDS - IA': [null,625,null,null,null,null],
  'CENTRAL NEW JERSEY - NJ': [null,175,null,null,null,null],
  'CHAMBERSBURG - PA': [null,375,null,null,null,null],
  'CHARLESTON - SC': [225,null,null,null,null,null],
  'CHARLESTON - WV': [null,500,null,null,null,500],
  'CHARLOTTE - NC': [350,null,null,null,null,325],
  'CHATTANOOGA - TN': [425,null,null,null,null,null],
  'CHICAGO - IL': [null,575,null,null,null,null],
  'CHICAGO NORTH - IL': [null,575,null,null,null,null],
  'CHICAGO SOUTH - IL': [null,575,null,null,null,null],
  'CHICAGO WEST - IL': [null,525,null,null,null,null],
  'CHINA GROVE - NC': [325,null,null,null,null,300],
  'CICERO-IN': [null,575,null,null,null,null],
  'CINCINNATI - OH': [null,450,null,null,null,null],
  'CINCINNATI / DAYTON - OH': [null,500,null,null,null,null],
  'CINCINNATI SOUTH - OH': [null,450,null,null,null,null],
  'CLEARWATER - FL': [300,null,null,null,null,null],
  'CLEVELAND - OH': [null,500,null,null,null,null],
  'CLEVELAND EAST - OH': [null,475,null,null,null,null],
  'CLEVELAND WEST - OH': [null,475,null,null,null,null],
  'CLEWISTON - FL': [350,null,null,null,null,null],
  'CLEWISTON SUBLOT - FL': [350,null,null,null,null,null],
  'COLORADO SPRINGS - CO': [null,null,675,700,null,null],
  'COLTON - CA': [null,null,190,null,null,null],
  'COLUMBIA - MO': [600,null,null,null,null,null],
  'COLUMBIA - SC': [200,null,null,null,null,null],
  'COLUMBIA - SC (SHA LIU)': [225,null,null,null,null,null],
  'COLUMBUS - OH': [null,450,null,null,null,null],
  'CONCORD - MA': [null,350,null,null,null,null],
  'CONCORD - NC': [300,null,null,null,null,275],
  'COPLAY - PA (Sublot)': [null,250,null,null,null,null],
  'CORPUS CHRISTI - TX': [null,null,null,250,null,null],
  'CRASHEDTOYS ATLANTA': [250,null,null,null,null,null],
  'CRASHEDTOYS DALLAS- TX': [null,null,null,250,null,null],
  'CRASHEDTOYS ELDRIDGE - IA': [null,750,null,null,null,null],
  'CULPEPER - VA': [null,375,null,null,null,325],
  'CUSSETA - AL': [425,null,null,null,null,null],
  'DALLAS - TX': [null,null,null,275,null,null],
  'DALLAS SOUTH - TX': [null,null,null,275,null,null],
  'DANVILLE - VA': [400,null,null,null,null,325],
  'DAVENPORT - IA': [null,625,null,null,null,null],
  'DAYTON - OH': [null,475,null,null,null,null],
  'DENVER - CO': [null,null,675,675,null,null],
  'DENVER CENTRAL - CO': [null,null,675,675,null,null],
  'DENVER SOUTH - CO': [null,null,675,675,null,null],
  'DES MOINES - IA': [null,625,null,null,null,null],
  'DETROIT - MI': [null,525,null,null,null,null],
  'DOTHAN - AL': [350,null,null,null,null,null],
  'DYER - IN': [600,null,null,null,null,null],
  'EARLINGTON – KY': [525,null,null,null,null,null],
  'EL PASO - TX': [null,null,null,450,null,null],
  'EUGENE - OR': [null,null,650,null,375,null],
  'EXETER - RI': [null,325,null,null,null,null],
  'FAIRBURN - GA': [300,null,null,null,null,null],
  'FAYETTEVILLE - AR': [null,null,null,475,null,null],
  'FLINT - MI': [null,550,null,null,null,null],
  'FORT WAYNE - IN': [null,600,null,null,null,null],
  'FREDERICKSBURG - VA': [null,325,null,null,null,300],
  'FREETOWN – MA': [null,350,null,null,null,null],
  'FREMONT - CA': [null,null,350,null,null,null],
  'FRESNO - CA': [null,null,275,null,null,null],
  'FT.PIERCE - FL': [350,null,null,null,null,null],
  'FT.WORTH - TX': [null,null,null,275,null,null],
  'Freetown – MA': [null,350,null,null,null,null],
  'GASTONIA - NC': [325,null,null,null,null,null],
  'GLASSBORO EAST - NJ': [null,225,null,null,null,null],
  'GLASSBORO WEST-NJ': [null,225,null,null,null,null],
  'GRAHAM - WA': [null,null,750,null,150,null],
  'GRAHAM - WA (YARD 377)': [null,null,750,null,150,null],
  'GREER - SC': [275,null,null,null,null,null],
  'GRENADA - MS': [450,null,null,null,null,null],
  'HAMMOND - IN': [null,600,null,null,null,null],
  'HAMPTON - VA': [null,350,null,null,null,250],
  'HARRISBURG - PA': [null,275,null,null,null,null],
  'HARTFORD - CT': [null,275,null,null,null,null],
  'HARTFORD - CT (North Sublot)': [null,275,null,null,null,null],
  'HARTFORD - CT (South Sublot)': [null,275,null,null,null,null],
  'HARTFORD SPRINGFIELD-CT': [null,225,null,null,null,null],
  'HAYWARD - CA': [null,null,350,null,null,null],
  'HELENA - MT': [null,null,950,null,750,null],
  'HONOLULU - HI': [null,null,null,null,null,null],
  'HOUSTON - TX': [null,null,null,200,null,null],
  'HOUSTON EAST-TX': [null,null,null,200,null,null],
  'INDIANAPOLIS - IN': [600,null,null,null,null,null],
  'IONIA - MI': [null,650,null,null,null,null],
  'JACKSON - MS': [375,null,null,null,null,null],
  'JACKSONVILLE EAST - FL': [200,null,null,null,null,null],
  'JACKSONVILLE NORTH -FL': [200,null,null,null,null,null],
  'JACKSONVILLE WEST - FL': [200,null,null,null,null,null],
  'KANSAS CITY - KS': [625,null,null,null,null,null],
  'KANSAS CITY EAST': [625,null,null,null,null,null],
  'KINCHELOE - MI': [null,975,null,null,null,null],
  'KNOXVILLE - TN': [375,null,null,null,null,null],
  'LAGRANGE - NC': [350,null,null,null,null,325],
  'LANSING - MI': [null,650,null,null,null,null],
  'LAS VEGAS - NV': [null,null,325,null,null,null],
  'LAS VEGAS WEST - NV': [null,null,325,null,null,null],
  'LEXINGTON EAST - KY': [525,null,null,null,null,null],
  'LEXINGTON WEST - KY': [525,null,null,null,null,null],
  'LINCOLN - NE': [null,625,null,null,null,null],
  'LITTLE ROCK - AR': [475,null,null,null,null,null],
  'LONG BEACH - CA': [null,null,140,null,null,null],
  'LONG ISLAND - NY': [null,250,null,null,null,null],
  'LONGVIEW - TX': [null,null,null,275,null,null],
  'LOS ANGELES - CA': [null,null,140,null,null,null],
  'LOUISVILLE - KY': [525,null,null,null,null,null],
  'LUFKIN - TX': [null,null,null,250,null,null],
  'LUMBERTON - NC': [300,null,null,null,null,300],
  'LYMAN - ME': [null,450,null,null,null,null],
  'MACON - GA': [250,null,null,null,null,null],
  'MADISON - WI': [675,null,null,null,null,null],
  'MADISON SOUTH - WI': [675,null,null,null,null,null],
  'MARTINEZ - CA': [null,null,350,null,null,null],
  'MCALLEN - TX': [null,null,null,325,null,null],
  'MEBANE - NC': [300,null,null,null,null,300],
  'MEMPHIS - TN': [500,null,null,null,null,null],
  'MENTONE - CA': [null,null,225,null,null,null],
  'MIAMI CENTRAL - FL': [350,null,null,null,null,null],
  'MIAMI NORTH - FL': [350,null,null,null,null,null],
  'MIAMI SOUTH - FL': [350,null,null,null,null,null],
  'MILWAUKEE - WI': [null,650,null,null,null,null],
  'MILWAUKEE NORTH-WI': [null,650,null,null,null,null],
  'MILWAUKEE SOUTH - WI': [null,650,null,null,null,null],
  'MINNEAPOLIS - MN': [950,675,null,null,null,null],
  'MINNEAPOLIS NORTH - MN': [950,675,null,null,null,null],
  'MOBILE - AL': [325,null,null,null,null,null],
  'MOBILE SOUTH - AL': [325,null,null,null,null,null],
  'MOCKSVILLE - NC': [300,null,null,null,null,300],
  'MONTGOMERY - AL': [375,null,null,null,null,null],
  'MULBERRY SUBLOT - FL': [300,null,null,null,null,null],
  'NAPA - CA': [null,null,450,null,null,null],
  'NASHVILLE - TN': [425,null,null,null,null,425],
  'NEW ORLEANS - LA': [400,null,null,null,null,null],
  'NEWBURGH - NY': [null,250,null,null,null,null],
  'NORTH BOSTON - MA': [null,325,null,null,null,null],
  'NORTH CHARLESTON': [225,null,null,null,null,null],
  'NORTH SEATTLE - WA': [null,null,750,null,225,null],
  'OCALA - FL': [300,null,null,null,null,null],
  'OGDEN- UT': [null,null,450,null,null,null],
  'OKLAHOMA CITY - OK': [null,null,null,425,null,null],
  'ORLANDO - FL': [300,null,null,null,null,null],
  'ORLANDO NORTH - FL': [300,null,null,null,null,null],
  'ORLANDO SOUTH - FL': [300,null,null,null,null,null],
  'PASCO - WA': [null,null,900,null,400,null],
  'PEORIA - IL': [null,600,null,null,null,null],
  'PHILADELPHIA - PA': [null,230,null,null,null,null],
  'PHILADELPHIA EAST': [null,230,null,null,null,null],
  'PHILADELPHIA EAST - SUBLOT': [null,null,null,null,null,null],
  'PHOENIX - AZ': [null,null,300,null,null,null],
  'PHOENIX NORTH - AZ': [null,null,330,null,null,null],
  'PITTSBURG SOUTH - PA': [null,425,null,null,null,null],
  'PITTSBURGH EAST - PA': [null,450,null,null,null,null],
  'PITTSBURGH NORTH - PA': [null,450,null,null,null,null],
  'PITTSBURGH WEST - PA': [null,450,null,null,null,null],
  'PORTLAND NORTH - OR': [null,null,650,null,275,null],
  'PORTLAND SOUTH - OR': [null,null,650,null,275,null],
  'PUNTA GORDA - FL': [325,null,null,null,null,null],
  'PUNTA GORDA SOUTH - FL': [325,null,null,null,null,null],
  'RALEIGH - NC': [300,null,null,null,null,300],
  'RALEIGH NORTH - NC': [300,null,null,null,null,300],
  'RANCHO CUCAMONGA - CA': [null,null,190,null,null,null],
  'RAPID CITY - SD': [null,1200,1250,null,1200,null],
  'REDDING - CA': [null,null,525,null,null,null],
  'RENO - NV': [null,null,500,null,null,null],
  'RICHMOND - VA': [null,375,null,null,null,300],
  'RICHMOND EAST-VA': [null,375,null,null,null,300],
  'ROCHESTER - NY': [null,400,null,null,null,null],
  'RUTLAND - VT': [null,475,null,null,null,null],
  'SACRAMENTO - CA': [null,null,375,null,null,null],
  'SALT LAKE CITY - UT': [null,null,450,null,null,null],
  'SAN ANTONIO - TX': [null,null,null,275,null,null],
  'SAN BERNARDINO- CA': [null,null,200,null,null,null],
  'SAN DIEGO - CA': [null,null,225,null,null,null],
  'SAN JOSE - CA': [null,null,350,null,null,null],
  'SAVANNAH - GA': [125,null,null,null,null,null],
  'SCRANTON - PA': [null,275,null,null,null,null],
  'SEAFORD - DE': [null,300,null,null,null,null],
  'SEAFORD - DE (Fruitland Sublot)': [null,325,null,null,null,null],
  'SHREVEPORT - LA': [null,null,null,300,null,null],
  'SIKESTON - MO': [600,null,null,null,null,null],
  'SO SACRAMENTO - CA': [null,null,375,null,null,null],
  'SO SACRAMENTO - CA (Sublot)': [null,null,375,null,null,null],
  'SOMERVILLE - NJ': [null,175,null,null,null,null],
  'SOUTH BOSTON - MA': [null,350,null,null,null,null],
  'SOUTHERN ILLINOIS - IL': [575,null,null,null,null,null],
  'SPANAWAY - WA': [null,null,725,null,150,null],
  'SPARTANBURG - SC': [300,null,null,null,null,null],
  'SPOKANE - WA': [null,null,900,null,375,null],
  'SPRINGFIELD - MO': [600,null,null,null,null,null],
  'ST. CLOUD - MN': [null,700,null,null,null,null],
  'ST. LOUIS - MO': [600,null,null,null,null,null],
  'ST. LOUIS - MO (Dunn Sublot)': [600,null,null,null,null,null],
  'SUN VALLEY - CA': [null,null,200,null,null,null],
  'SYRACUSE - NY': [null,325,null,null,null,null],
  'TALLAHASSEE - FL': [300,null,null,null,null,null],
  'TAMPA NORTH - FL': [300,null,null,null,null,null],
  'TAMPA SOUTH - FL': [300,null,null,null,null,null],
  'TAMPA SOUTH - FL (YD335)': [300,null,null,null,null,null],
  'TANNER - AL': [400,null,null,null,null,null],
  'TIFTON - GA': [250,null,null,null,null,null],
  'TORONTO CANADA': [null,null,null,null,null,null],
  'TRENTON - NJ': [null,225,null,null,null,null],
  'TRENTON - NJ (Jobstown Sublot)': [null,225,null,null,null,null],
  'TRENTON - NJ (YD174 SUBLOT)': [null,450,null,null,null,null],
  'TRENTON - NJ (YD329 Sublot)': [null,225,null,null,null,null],
  'TUCSON - AZ': [null,null,375,null,null,null],
  'TULSA - OK': [null,null,null,475,null,null],
  'VALLEJO - CA': [null,null,375,null,null,null],
  'VALLEJO - CA (Sublot)': [null,null,400,null,null,null],
  'VAN NUYS - CA': [null,null,180,null,null,null],
  'VINTON - LA': [null,null,null,325,null,null],
  'WACO - TX': [null,null,null,275,null,null],
  'WALTON - KY': [525,null,null,null,null,null],
  'WASHINGTON DC - MD': [null,300,null,null,null,300],
  'WAYLAND - MI': [null,650,null,null,null,null],
  'WEBSTER - NH': [null,null,null,null,null,null],
  'WEST PALM BEACH - FL': [350,null,null,null,null,null],
  'WEST WARREN - MA': [null,325,null,null,null,null],
  'WHEELING - IL': [null,550,null,null,null,null],
  'WICHITA - KS': [null,null,null,475,null,null],
  'WINDHAM - ME': [null,500,null,null,null,null],
  'YORK HAVEN - PA': [null,275,null,null,null,null],
};