const IAAI_RATES = {
  'ABILENE - TX': [null,null,null,425,null,null],
  'ACE - PERRIS 2 - CA': [null,null,200,null,null,null],
  'ACE CARSON - CA': [null,null,150,null,null,null],
  'ACE-PERRIS': [null,null,200,null,null,null],
  'ACRON CANTON - OH': [null,475,null,null,null,null],
  'ADESA BIRMINGHAM - AL': [350,null,null,null,null,null],
  'ALBANY - NY': [null,250,null,null,null,null],
  'ALBUQUERQUE - NM': [null,null,700,700,null,null],
  'ALTOONA - PA': [null,425,null,null,null,null],
  'AMARILLO - TX': [null,null,null,425,null,null],
  'ANAHEIM - CA': [null,null,160,null,null,null],
  'ANAHEIM CONSOLIDATED – CA': [null,null,null,null,null,null],
  'ANCHORAGE - AK': [null,null,2650,null,1850,null],
  'APPLETON - WI': [725,null,null,null,null,null],
  'ASHEVILLE - NC': [325,null,null,null,null,325],
  'ASHLAND - KY': [700,null,null,null,null,null],
  'ATLANTA - GA': [300,null,null,null,null,null],
  'ATLANTA EAST - GA': [300,null,null,null,null,null],
  'ATLANTA NORTH - GA': [300,null,null,null,null,null],
  'ATLANTA SOUTH - GA': [300,null,null,null,null,null],
  'ATLANTA WEST - GA': [300,null,null,null,null,null],
  'AUSTIN - TX': [null,null,null,275,null,null],
  'AUSTIN NORTH - TX': [null,null,null,275,null,null],
  'AVENEL - NJ': [null,150,null,null,null,null],
  'BALTIMORE - MD': [null,300,null,null,null,300],
  'BATON ROUGE - LA': [400,null,null,null,null,null],
  'BILLINGS - MT': [null,null,1050,1250,850,null],
  'BIRMINGHAM - AL': [375,null,null,null,null,null],
  'BOISE - ID': [null,null,750,null,475,null],
  'BOSTON-SHIRLEY - MA': [null,350,null,null,null,null],
  'BOWLING GREEN - KY': [550,null,null,null,null,null],
  'BRIDGEPORT - PA': [null,250,null,null,null,null],
  'BUCKHANNON - WV': [null,500,null,null,null,500],
  'BUFFALO - NY': [null,475,null,null,null,null],
  'BURLINGTON - VT': [null,500,null,null,null,null],
  'CASPER - WY': [null,null,1400,null,1300,null],
  'CENTRAL NEW JERSEY - NJ': [null,175,null,null,null,null],
  'CHARLESTON - SC': [225,null,null,null,null,null],
  'CHARLOTTE - NC': [350,null,null,null,null,325],
  'CHATTANOOGA - TN': [425,null,null,null,null,null],
  'CHICAGO NORTH - IL': [null,575,null,null,null,null],
  'CHICAGO SOUTH - IL': [null,575,null,null,null,null],
  'CHICAGO WEST - IL': [null,525,null,null,null,null],
  'CINCINNATI - OH': [null,450,null,null,null,null],
  'CINCINNATI SOUTH - OH': [null,450,null,null,null,null],
  'CLEARWATER - FL': [300,null,null,null,null,null],
  'CLEVELAND - OH': [null,500,null,null,null,null],
  'CLEWISTON SUBLOT - FL': [350,null,null,null,null,null],
  'COLORADO SPRINGS - CO': [null,null,675,700,null,null],
  'COLTON - CA': [null,null,190,null,null,null],
  'COLUMBIA - SC': [200,null,null,null,null,null],
  'COLUMBUS - OH': [null,450,null,null,null,null],
  'CONCORD - NC': [300,null,null,null,null,275],
  'CORPUS CHRISTI - TX': [null,null,null,250,null,null],
  'CULPEPER - VA': [null,375,null,null,null,325],
  'DALLAS - TX': [null,null,null,275,null,null],
  'DALLAS / FT. WORTH - TX': [null,null,null,275,null,null],
  'DAVENPORT - IA': [null,625,null,null,null,null],
  'DAYTON - OH': [null,475,null,null,null,null],
  'DENVER - CO': [null,null,675,675,null,null],
  'DENVER EAST - CO': [null,null,675,675,null,null],
  'DES MOINES - IA': [null,625,null,null,null,null],
  'DETROIT - MI': [null,525,null,null,null,null],
  'DOTHAN - AL': [350,null,null,null,null,null],
  'DUNDALK - MD': [null,300,null,null,null,300],
  'EAST BAY - CA': [null,null,350,null,null,null],
  'EL PASO - TX': [null,null,null,450,null,null],
  'ELKTON – MD': [null,275,null,null,null,null],
  'ENGLISHTOWN - NJ': [null,175,null,null,null,null],
  'ERIE - PA': [null,525,null,null,null,null],
  'EUGENE - OR': [null,null,650,null,375,null],
  'FARGO - ND': [null,1100,null,null,null,null],
  'FAYETTEVILLE - AR': [null,null,null,475,null,null],
  'FLINT - MI': [null,550,null,null,null,null],
  'FONTANA - CA': [null,null,190,null,null,null],
  'FORT MYERS - FL': [375,null,null,null,null,null],
  'FORT MYERS - FL (Sublot)': [375,null,null,null,null,null],
  'FORT WAYNE - IN': [null,600,null,null,null,null],
  'FORT WORTH NORTH - TX': [null,null,null,275,null,null],
  'FREDERICKSBURG-SOUTH - VA': [null,325,null,null,null,300],
  'FREMONT - CA': [null,null,350,null,null,null],
  'FRESNO - CA': [null,null,275,null,null,null],
  'FT.PIERCE - FL': [350,null,null,null,null,null],
  'GRAND RAPIDS - MI': [null,650,null,null,null,null],
  'GREAT LAKES - MI': [null,null,null,null,null,null],
  'GREENSBORO - NC': [325,null,null,null,null,325],
  'GREENVILLE - SC': [325,null,null,null,null,null],
  'GRENADA - MS': [450,null,null,null,null,null],
  'GULF COAST - MS': [325,null,null,null,null,null],
  'HARTFORD - CT': [null,275,null,null,null,null],
  'HARTFORD SOUTH - CT': [null,275,null,null,null,null],
  'HIGH DESERT - CA': [null,null,225,null,null,null],
  'HIGH POINT - NC': [325,null,null,null,null,null],
  'HONOLULU - HI': [null,null,null,null,null,null],
  'HOUSTON - TX': [null,null,null,200,null,null],
  'HOUSTON NORTH - TX': [null,null,null,200,null,null],
  'HOUSTON SOUTH': [null,null,null,200,null,null],
  'HOUSTON SOUTH - TX': [null,null,null,200,null,null],
  'HUNTSVILLE - AL': [375,null,null,null,null,null],
  'INDIANAPOLIS - IN': [600,null,null,null,null,null],
  'INDIANAPOLIS SOUTH - IN': [600,null,null,null,null,null],
  'JACKSON - MS': [375,null,null,null,null,null],
  'JACKSONVILLE - FL': [200,null,null,null,null,null],
  'KANSAS CITY - KS': [625,null,null,null,null,null],
  'KANSAS CITY EAST': [625,null,null,null,null,null],
  'KNOXVILLE - TN': [375,null,null,null,null,null],
  'LAFAYETTE - LA': [375,null,null,null,null,null],
  'LAKE CITY - GA': [325,null,null,null,null,null],
  'LAS VEGAS - NV': [null,null,325,null,null,null],
  'LAUREL - MD': [null,300,null,null,null,null],
  'LEXINGTON - SC': [225,null,null,null,null,null],
  'LINCOLN - IL': [null,625,null,null,null,null],
  'LITTLE ROCK - AR': [475,null,null,null,null,null],
  'LONG ISLAND - NY': [null,250,null,null,null,null],
  'LONGVIEW - TX': [null,null,null,275,null,null],
  'LOS ANGELES - CA': [null,null,140,null,null,null],
  'LOS ANGELES SOUTH - CA': [null,null,140,null,null,null],
  'LOUISVILLE - KY': [525,null,null,null,null,null],
  'LOUISVILLE NORTH - KY': [525,null,null,null,null,null],
  'LUBBOCK - TX': [null,null,null,475,null,null],
  'MACON - GA': [250,null,null,null,null,null],
  'MANCHESTER - NH': [null,375,null,null,null,null],
  'MCALLEN - TX': [null,null,null,325,null,null],
  'MEMPHIS - TN': [500,null,null,null,null,null],
  'METRO - DC': [null,300,null,null,null,300],
  'MIAMI - FL': [350,null,null,null,null,null],
  'MIAMI NORTH - FL': [350,null,null,null,null,null],
  'MIAMI NORTH - FL (SUBLOT 2)': [350,null,null,null,null,null],
  'MILWAUKEE - WI': [null,650,null,null,null,null],
  'MINNEAPOLIS/SOUTH - MN': [950,675,null,null,null,null],
  'MINNEAPOLIS/ST.PAUL - MN': [950,675,null,null,null,null],
  'MISSOULA - MT': [null,null,1150,null,700,null],
  'MOBILE - AL': [325,null,null,null,null,null],
  'MONTICELLO - NY': [null,275,null,null,null,null],
  'MONTICELLO SUBLOT - NY': [null,275,null,null,null,null],
  'NASHVILLE - TN': [425,null,null,null,null,425],
  'NEW CASTLE - DE': [null,275,null,null,null,null],
  'NEW ORLEANS - LA': [400,null,null,null,null,null],
  'NEW ORLEANS EAST - LA': [400,null,null,null,null,null],
  'NEWBURGH - NY': [null,250,null,null,null,null],
  'NORTH HOLLYWOOD - CA': [null,null,180,null,null,null],
  'NORTHERN VIRGINIA - VA': [null,325,null,null,null,300],
  'OKLAHOMA CITY - OK': [null,null,null,425,null,null],
  'OMAHA - NE': [null,650,null,null,null,null],
  'OMAHA SOUTH - NE': [null,650,null,null,null,null],
  'ORLANDO - FL': [300,null,null,null,null,null],
  'ORLANDO - FL (Boggy Sublot)': [300,null,null,null,null,null],
  'ORLANDO NORTH - FL': [300,null,null,null,null,null],
  'PADUCAH - KY': [575,null,null,null,null,null],
  'PENSACOLA - FL': [400,null,null,null,null,null],
  'PERMIAN BASIN - TX': [null,null,null,425,null,null],
  'PHILADELPHIA - PA': [null,230,null,null,null,null],
  'PHOENIX - AZ': [null,null,300,null,null,null],
  'PITTSBURGH - PA': [null,450,null,null,null,null],
  'PITTSBURGH NORTH - PA': [null,450,null,null,null,null],
  'PORT MURRAY - NJ': [null,225,null,null,null,null],
  'PORTAGE - WI': [null,625,null,null,null,null],
  'PORTLAND - OR': [null,null,650,null,250,null],
  'PORTLAND GORHAM - ME': [null,425,null,null,null,null],
  'PORTLAND NORTH - OR': [null,null,650,null,275,null],
  'PORTLAND SOUTH - OR': [null,null,650,null,275,null],
  'PORTLAND WEST - OR': [null,null,650,null,275,null],
  'PROVIDENCE - RI': [null,325,null,null,null,null],
  'PROVO - UT': [null,null,475,null,null,null],
  'PULASKI - VA': [450,null,null,null,null,450],
  'RALEIGH - NC': [300,null,null,null,null,300],
  'RENO - NV': [null,null,500,null,null,null],
  'RICHMOND - VA': [null,375,null,null,null,300],
  'RIVERSIDE – CA': [null,null,190,null,null,null],
  'ROANOKE - VA': [null,425,null,null,null,400],
  'ROCHESTER - NY': [null,400,null,null,null,null],
  'ROCHESTER WEST - NY': [null,400,null,null,null,null],
  'ROSEDALE - MD': [null,null,null,null,null,null],
  'SACRAMENTO - CA': [null,null,375,null,null,null],
  'SACRAMENTO WEST - CA': [null,null,400,null,null,null],
  'SALT LAKE CITY - UT': [null,null,450,null,null,null],
  'SAN ANTONIO - TX': [null,null,null,275,null,null],
  'SAN ANTONIO SOUTH - TX': [null,null,null,275,null,null],
  'SAN DIEGO - CA': [null,null,225,null,null,null],
  'SANTA CLARITA - CA': [null,null,220,null,null,null],
  'SAVANNAH - GA': [125,null,null,null,null,null],
  'SAYREVILLE - NJ': [null,160,null,null,null,null],
  'SCRANTON - PA': [null,275,null,null,null,null],
  'SEATLE - WA': [null,null,750,null,150,null],
  'SEATLE SOUTH - WA': [null,null,750,null,150,null],
  'SHADY SPRING - WV': [null,500,null,null,null,500],
  'SHREVEPORT - LA': [null,null,null,300,null,null],
  'SIOUX FALLS - SD': [null,1000,null,null,null,null],
  'SOUTH BEND - IN': [null,575,null,null,null,null],
  'SOUTHERN NEW JERSEY - NJ': [null,225,null,null,null,null],
  'SPECIALTY DIVISION - IL': [null,null,null,null,null,null],
  'SPOKANE - WA': [null,null,900,null,375,null],
  'SPRINGFIELD - MO': [600,null,null,null,null,null],
  'ST. CLOUD - MN': [null,700,null,null,null,null],
  'ST. LOUIS - IL': [600,null,null,null,null,null],
  'STOCKTON - CA': [null,null,350,null,null,null],
  'SUFFOLK - VA': [null,350,null,null,null,225],
  'SYRACUSE - NY': [null,325,null,null,null,null],
  'South Bend - IN (Sublot)': [null,575,null,null,null,null],
  'TAMPA - FL': [300,null,null,null,null,null],
  'TAMPA - FL (Cat Yard 4)': [300,null,null,null,null,null],
  'TAMPA NORTH - FL': [300,null,null,null,null,null],
  'TAUNTON - MA': [null,325,null,null,null,null],
  'TEMPLETON-MA': [null,350,null,null,null,null],
  'TIDEWATER - VA': [null,325,null,null,null,240],
  'TIFTON - GA': [250,null,null,null,null,null],
  'TUCSON - AZ': [null,null,375,null,null,null],
  'TULSA - OK': [null,null,null,475,null,null],
  'WEST PALM BEACH - FL': [350,null,null,null,null,null],
  'WESTERN COLORADO - CO': [null,null,null,975,null,null],
  'WICHITA - KS': [null,null,null,475,null,null],
  'WILMINGTON - NC': [325,null,null,null,null,325],
  'YORK SPRINGS - PA': [null,275,null,null,null,null],
};